name: golang CI-dev

on: [push]

jobs:
  CI-dev:
    runs-on: ubuntu-latest

    # container:
    #   image: ubuntu:latest
    #   options: --user 0

    env:
      AWS_ACCESS_KEY_ID: "123"
      AWS_SECRET_ACCESS_KEY: "123"
      AWS_DEFAULT_REGION: ap-southeast-1

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sls-go-mod
        uses: actions/checkout@v2

      - name: Print dir
        run: ls

      - name: Update ubuntu
        run: sudo apt-get -qq update

      - name: Install curl, jq, make, zip, ping, net-tools
        run:  sudo apt-get -qq -y install curl jq build-essential zip iputils-ping net-tools

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install Go modules, gotest and golangci-lint
        run: go mod download && make install-gotest && sudo make install-lint

      - name: Run test
        run: make test-notify

      - name: Run lint
        run: make lint-notify


