name: go-monorepo CI

on: [push]

jobs:
  CI-dev:
    runs-on: ubuntu-latest

    # container:
    #   image: ubuntu:latest
    #   options: --user 0

    env:
      PORT: 4000

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sls-go-mod
        uses: actions/checkout@v2
      - name: Print dir
        run: ls
      - name: Update ubuntu
        run: sudo apt-get -qq update
      - name: Install curl, jq, make, zip, ping, net-tools
        run:  sudo apt-get -qq -y install curl jq build-essential zip iputils-ping net-tools
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Install Go modules
        run: go mod download
      - name: Install golangci-lint, docker-compose
          sudo make install-lint
          sudo make install-docker-compose
      - name: Run test
        run: make test-greet
      - name: Run lint
        run: make lint-greet
